"""Initial migration

Revision ID: 32c7318f2959
Revises: 
Create Date: 2024-10-01 20:17:22.584553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c7318f2959'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('joke_type', sa.String(length=50), nullable=True),
    sa.Column('joke_text', sa.String(length=255), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('political', sa.Boolean(), nullable=True),
    sa.Column('sexist', sa.Boolean(), nullable=True),
    sa.Column('safe', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke')
    # ### end Alembic commands ###
