"""Initial migration

Revision ID: fac2758647eb
Revises: 32c7318f2959
Create Date: 2024-10-02 21:56:39.445194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac2758647eb'
down_revision = '32c7318f2959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('joke', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('setup', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery', sa.Text(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('joke_text')
        batch_op.drop_column('joke_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joke_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('joke_text', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('delivery')
        batch_op.drop_column('setup')
        batch_op.drop_column('joke')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
